# Generated by Django 4.2.2 on 2023-06-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohorte',
            name='number',
            field=models.IntegerField(default=9),
        ),
    ]
